[project]
name = "weather-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Future-Rafay", email = "rafaynadeem77@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []
